# Generated by Django 3.2 on 2021-12-21 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(blank=True, db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'company"."department',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(blank=True, db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=511, verbose_name='fullname')),
                ('foto', models.FileField(blank=True, null=True, upload_to='persons/', verbose_name='foto')),
                ('salary', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='salary')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16)], verbose_name='age')),
                ('position', models.CharField(choices=[('architect', 'architect'), ('lead', 'lead'), ('developer', 'developer'), ('manager', 'manager')], max_length=30, verbose_name='position')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': 'company"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonDepartment',
            fields=[
                ('id', models.UUIDField(blank=True, db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='company.department')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='company.person')),
            ],
            options={
                'db_table': 'company"."person_department',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ManyToManyField(through='company.PersonDepartment', to='company.Department'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(db_column='head_id', on_delete=django.db.models.deletion.PROTECT, related_name='hdepartment', to='company.person'),
        ),
        migrations.AddConstraint(
            model_name='persondepartment',
            constraint=models.UniqueConstraint(fields=('person', 'department'), name='unique_person_department'),
        ),
    ]
